### ISSUE TITLE
右上角点击功能按钮报错

### ISSUE THREAD

**Issue by YEMAOYANG** [HanawaHinata/wfd-vue3#2]
项目右上角点击“预览流程”、“获取数据”报错：
runtime-core.esm-bundler.js:265 
 Uncaught TypeError: this.get is not a function
    at AbstractGraph.save (graph.js:2104:1)
    at getGraphData (App.vue:103:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:1)
    at emit (runtime-core.esm-bundler.js:725:1)
    at eval (runtime-core.esm-bundler.js:7819:1)
    at handleClick (button.js:128:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:1)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:696:1)

**Comment by HanawaHinata** [comment]
这块没做完，现阶段项目只是能跑起来...有空会完善下

**Comment by HanawaHinata** [comment]
问题已解决，感谢协助指出问题
